# Generated by Django 4.1.7 on 2023-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('image_id', models.CharField(max_length=100)),
                ('solution_id', models.CharField(max_length=100)),
                ('theoryimage_id', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
            ],
        ),
    ]
