# Generated by Django 4.1.7 on 2023-04-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Accounttest',
        ),
    ]
